--liquibase formatted sql

--changeset insert-data:1 dbms:postgresql context:main
INSERT INTO categories (name)
VALUES ('conversational'), ('technologies'), ('slang'), ('finance');

--changeset insert-data:2 dbms:postgresql context:main
INSERT INTO words (word, transcription, translation, partofspeech, category_id) VALUES
-- Category 1: Conversional (25 слов)
('hello', '/həˈloʊ/', 'привет', 'interjection', 1),
('goodbye', '/ɡʊdˈbaɪ/', 'до свидания', 'interjection', 1),
('please', '/pliːz/', 'пожалуйста', 'adverb', 1),
('thank you', '/ˈθæŋk juː/', 'спасибо', 'interjection', 1),
('sorry', '/ˈsɑː.ri/', 'извините', 'adjective', 1),
('yes', '/jes/', 'да', 'adverb', 1),
('no', '/noʊ/', 'нет', 'adverb', 1),
('maybe', '/ˈmeɪ.bi/', 'возможно', 'adverb', 1),
('help', '/help/', 'помощь', 'noun', 1),
('question', '/ˈkwes.tʃən/', 'вопрос', 'noun', 1),
('answer', '/ˈæn.sɚ/', 'ответ', 'noun', 1),
('understand', '/ˌʌn.dɚˈstænd/', 'понимать', 'verb', 1),
('explain', '/ɪkˈspleɪn/', 'объяснять', 'verb', 1),
('listen', '/ˈlɪs.ən/', 'слушать', 'verb', 1),
('speak', '/spiːk/', 'говорить', 'verb', 1),
('meet', '/miːt/', 'встречать', 'verb', 1),
('friend', '/frend/', 'друг', 'noun', 1),
('family', '/ˈfæm.əl.i/', 'семья', 'noun', 1),
('home', '/hoʊm/', 'дом', 'noun', 1),
('work', '/wɝːk/', 'работа', 'noun', 1),
('time', '/taɪm/', 'время', 'noun', 1),
('day', '/deɪ/', 'день', 'noun', 1),
('night', '/naɪt/', 'ночь', 'noun', 1),
('food', '/fuːd/', 'еда', 'noun', 1),
('water', '/ˈwɑː.t̬ɚ/', 'вода', 'noun', 1),

-- Category 2: Technologies (35 слов)
('computer', '/kəmˈpjuː.tər/', 'компьютер', 'noun', 2),
('software', '/ˈsɒft.weər/', 'программное обеспечение', 'noun', 2),
('hardware', '/ˈhɑːrd.wer/', 'аппаратное обеспечение', 'noun', 2),
('algorithm', '/ˈæl.ɡə.rɪ.ðəm/', 'алгоритм', 'noun', 2),
('database', '/ˈdeɪ.tə.beɪs/', 'база данных', 'noun', 2),
('network', '/ˈnet.wɝːk/', 'сеть', 'noun', 2),
('internet', '/ˈɪn.t̬ɚ.net/', 'интернет', 'noun', 2),
('website', '/ˈweb.saɪt/', 'веб-сайт', 'noun', 2),
('application', '/ˌæp.lɪˈkeɪ.ʃən/', 'приложение', 'noun', 2),
('programming', '/ˈproʊ.ɡræm.ɪŋ/', 'программирование', 'noun', 2),
('developer', '/dɪˈvel.ə.pɚ/', 'разработчик', 'noun', 2),
('code', '/koʊd/', 'код', 'noun', 2),
('debug', '/ˌdiːˈbʌɡ/', 'отлаживать', 'verb', 2),
('compile', '/kəmˈpaɪl/', 'компилировать', 'verb', 2),
('execute', '/ˈek.sɪ.kjuːt/', 'выполнять', 'verb', 2),
('cloud', '/klaʊd/', 'облако', 'noun', 2),
('server', '/ˈsɝː.vɚ/', 'сервер', 'noun', 2),
('client', '/ˈklaɪ.ənt/', 'клиент', 'noun', 2),
('mobile', '/ˈmoʊ.bəl/', 'мобильный', 'adjective', 2),
('digital', '/ˈdɪdʒ.ə.t̬əl/', 'цифровой', 'adjective', 2),
('virtual', '/ˈvɝː.tʃu.əl/', 'виртуальный', 'adjective', 2),
('artificial', '/ˌɑːr.t̬əˈfɪʃ.əl/', 'искусственный', 'adjective', 2),
('intelligence', '/ɪnˈtel.ə.dʒəns/', 'интеллект', 'noun', 2),
('machine', '/məˈʃiːn/', 'машина', 'noun', 2),
('learning', '/ˈlɝː.nɪŋ/', 'обучение', 'noun', 2),
('data', '/ˈdeɪ.t̬ə/', 'данные', 'noun', 2),
('analytics', '/ˌæn.əˈlɪt̬.ɪks/', 'аналитика', 'noun', 2),
('cybersecurity', '/ˈsaɪ.bɚ.sɪ.kjʊr.ə.ti/', 'кибербезопасность', 'noun', 2),
('encryption', '/ɪnˈkrɪp.ʃən/', 'шифрование', 'noun', 2),
('blockchain', '/ˈblɒk.tʃeɪn/', 'блокчейн', 'noun', 2),
('interface', '/ˈɪn.t̬ɚ.feɪs/', 'интерфейс', 'noun', 2),
('responsive', '/rɪˈspɒn.sɪv/', 'адаптивный', 'adjective', 2),
('scalable', '/ˈskeɪ.lə.bəl/', 'масштабируемый', 'adjective', 2),
('agile', '/ˈædʒ.aɪl/', 'гибкий', 'adjective', 2),
('framework', '/ˈfreɪm.wɝːk/', 'фреймворк', 'noun', 2),

-- Category 3: Slang (20 слов)
('lit', '/lɪt/', 'круто', 'adjective', 3),
('vibe', '/vaɪb/', 'атмосфера', 'noun', 3),
('savage', '/ˈsæv.ɪdʒ/', 'жесткий', 'adjective', 3),
('ghost', '/ɡoʊst/', 'исчезать', 'verb', 3),
('flex', '/fleks/', 'хвастаться', 'verb', 3),
('woke', '/woʊk/', 'проснувшийся', 'adjective', 3),
('stan', '/stæn/', 'фанат', 'noun', 3),
('ship', '/ʃɪp/', 'отношения', 'verb', 3),
('thirsty', '/ˈθɝː.sti/', 'отчаянный', 'adjective', 3),
('salty', '/ˈsɑːl.ti/', 'раздраженный', 'adjective', 3),
('basic', '/ˈbeɪ.sɪk/', 'обычный', 'adjective', 3),
('extra', '/ˈek.strə/', 'чрезмерный', 'adjective', 3),
('mood', '/muːd/', 'настроение', 'noun', 3),
('bet', '/bet/', 'договорились', 'interjection', 3),
('cap', '/kæp/', 'ложь', 'noun', 3),
('dope', '/doʊp/', 'отличный', 'adjective', 3),
('gucci', '/ˈɡuː.tʃi/', 'хороший', 'adjective', 3),
('slay', '/sleɪ/', 'убивать', 'verb', 3),
('yeet', '/jiːt/', 'бросать', 'verb', 3),
('sus', '/sʌs/', 'подозрительный', 'adjective', 3),

-- Category 4: Finance (20 слов)
('investment', '/ɪnˈvest.mənt/', 'инвестиция', 'noun', 4),
('stock', '/stɑːk/', 'акция', 'noun', 4),
('bond', '/bɑːnd/', 'облигация', 'noun', 4),
('dividend', '/ˈdɪv.ə.dend/', 'дивиденд', 'noun', 4),
('portfolio', '/pɔːrtˈfoʊ.li.oʊ/', 'портфель', 'noun', 4),
('asset', '/ˈæs.et/', 'актив', 'noun', 4),
('liability', '/ˌlaɪ.əˈbɪl.ə.t̬i/', 'обязательство', 'noun', 4),
('equity', '/ˈek.wə.t̬i/', 'собственный капитал', 'noun', 4),
('revenue', '/ˈrev.ə.nuː/', 'доход', 'noun', 4),
('profit', '/ˈprɑː.fɪt/', 'прибыль', 'noun', 4),
('loss', '/lɔːs/', 'убыток', 'noun', 4),
('budget', '/ˈbʌdʒ.ɪt/', 'бюджет', 'noun', 4),
('interest', '/ˈɪn.trəst/', 'процент', 'noun', 4),
('inflation', '/ɪnˈfleɪ.ʃən/', 'инфляция', 'noun', 4),
('deflation', '/ˌdiːˈfleɪ.ʃən/', 'дефляция', 'noun', 4),
('currency', '/ˈkɝː.ən.si/', 'валюта', 'noun', 4),
('exchange', '/ɪksˈtʃeɪndʒ/', 'обмен', 'noun', 4),
('market', '/ˈmɑːr.kɪt/', 'рынок', 'noun', 4),
('trade', '/treɪd/', 'торговля', 'noun', 4),
('bank', '/bæŋk/', 'банк', 'noun', 4);